#!/bin/sh

# Copyright © 2022 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -ex

: "${DEVICE_SMP:=1}"
: "${DEVICE_MEM_MB:=512}"

# firmware
if [ $3 != "" ]; then
  FIRMWARE="-bios ${3}"
fi

# run
"qemu-system-${1}" \
  -machine "${DEVICE_BOARD:-virt}" \
  -smp "${DEVICE_SMP}" \
  -m "${DEVICE_MEM_MB}M" \
  ${FIRMWARE} \
  -kernel "${2}" \
  -object rng-random,id=rng0,filename=/dev/urandom \
  -serial mon:stdio \
  -nographic
